name: pr
on:
  push:
    branches-ignore:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  linting:
    name: "linting"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: false

      - name: Python 3
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install yamllint
        run: pip3 install yamllint

      - name: Lint code.
        run: |
          yamllint -f standard .

  kustomize:
    name: "kustomize"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: false

      - name: kustomize
        run: kustomize build .
